---
title: "R Notebook"
output: html_notebook
---
```{r}
library(data.table)     # Run once per session
library(ggplot2)        # Run once per session
library(igraph)         # Run once per session
library(bslib)
library(leaflet)
library(shiny)
```

```{r}
dt.trade <- fread("../../data/cleaned_trade_data.csv")

# Save dt.movie.actor. Next time you can simply call the load function (below)
save(dt.trade, file="trade.RData") 

# Load previously saved dt.trade You can start in this line if you have previously saved these data.
load("trade.RData") 

dt.trade <- fread("../../data/cleaned_trade_data.csv")
```

Exploratory Data Analaysis and Data Cleaning 

```{r}
#how many rows does our data set contain 
nrow(dt.trade)

#what are the different columns in our data set
colnames(dt.trade)

#countrylist
l.countries <- as.list(unique(dt.trade$reporter_name))
l.continent <- as.list(unique(dt.trade$reporter_continent))

```

Network

```{r}
# Set the parameters
dt.trade.country <- dt.trade[reporter_name == "Afghanistan"]

dt.trade.country.year <- dt.trade.country[year == 2018]

# Set the vertices
all.importers <- dt.trade.country.year[, list(name=unique(reporter_name), type=TRUE)]
all.exporters <- dt.trade.country.year[, list(name=unique(partner_name), type=FALSE)]

all.vertices <- rbind(all.importers, all.exporters)

# Create & plot the graph
g1 <- graph.data.frame(dt.trade.country.year[, list(reporter_name, partner_name)],
      directed=TRUE, vertices=all.vertices)

plot(g1, vertex.size = 5, vertex.label = NA)

#g2 <- graph.data.frame(dt.trade[, list(reporter_name, partner_name)], directed=FALSE)
#summary(g) 
#plot(g)
```
```{r}
# Get number of nodes/vertices
num_nodes <- vcount(g1)

# Get number of edges
num_edges <- ecount(g1)

# Get degree of each vertex/country
degrees <- degree(g1)

# Calculate average and median degree, ignoring NA values
avg_degree <- mean(degrees, na.rm = TRUE)
med_degree <- median(degrees, na.rm = TRUE)


# Get edge weights, ignoring NA values
edge_weights <- E(g1)$trade_value_usd[!is.na(E(g1)$trade_value_usd)]

# Calculate statistics on edge weights, ignoring NA values
avg_weight <- mean(edge_weights, na.rm = TRUE)
med_weight <- median(edge_weights, na.rm = TRUE)
min_weight <- min(edge_weights, na.rm = TRUE)
max_weight <- max(edge_weights, na.rm = TRUE)
sd_weight <- sd(edge_weights, na.rm = TRUE)

# Create data.table with results
result_dt <- data.table(num_nodes = num_nodes,
                        num_edges = num_edges,
                        avg_degree = avg_degree,
                        med_degree = med_degree,
                        avg_weight_usd = avg_weight,
                        med_weight_usd = med_weight,
                        min_weight_usd = min_weight,
                        max_weight_usd = max_weight,
                        sd_weight_usd = sd_weight)

print(result_dt)

```

```{r}
ui <- fluidPage(
  
  # App title ----
  titlePanel("Shiny App for International Trade"),
  
  navbarPage(title = "Network Analytics",
             theme = bs_theme(bg = "white",
                              fg = "black",
                              primary = "maroon",
                              base_font = font_google("Montserrat")
             )
  ),
  
  sidebarLayout(
    
    # Inputs: Select variables to plot
    sidebarPanel(
      
      img(src = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/World_Trade_Organization_%28logo_and_wordmark%29.svg/2560px-World_Trade_Organization_%28logo_and_wordmark%29.svg.png",width="100%"),
      
      # Select Trade
      selectInput(inputId = "trader", 
                  label = "Select Imports or Exports:",
                  choices = c("Exports"="reporter_name","Imports"="partner_name"), 
                  selected = "reporter_name"),
      
      # Select continent
      selectInput(inputId = "continent", 
                  label = "Select Continent:",
                  choices = l.continent, 
                  selected = "Africa"),
      
      # Set year range
      selectInput(inputId = "year",
                  label = "Year:",
                  choices = c(levels(as.factor(dt.trade$year))),
                  selected = "2017",
                  multiple = FALSE)
    ),
    
    
    # Output: Show network and map
    mainPanel(
      
      # Show the map
      leafletOutput(outputId = "map"),
      
      # Show the network
      plotOutput(outputId = "plot")
    )
  )
)

```

```{r}
server <- function(input, output) {
  
  # Filter the data by the selected continent and year
  filtered_data <- reactive({
    dt.trade %>%
      filter(reporter_continent == input$continent,
             year == input$year)
  })
  
  # Render the map
  output$map <- renderLeaflet({
    leaflet() %>%
      addTiles() %>%
      addMarkers(data = filtered_data(),
                 lat = ~reporter.lat,
                 lng = ~reporter.long,
                 popup = ~reporter_name)
  })
  
  # Render the network
  output$plot <- renderPlot({
    # Your code for plotting the network goes here
  })
  
}

```

```{r}
shinyApp(ui, server)
```
